function Hd = my_kaiser
%KAISER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 10-May-2019 00:28:29

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

Fstop1 = 0.18;            % First Stopband Frequency
Fpass1 = 0.2;             % First Passband Frequency
Fpass2 = 0.5;             % Second Passband Frequency
Fstop2 = 0.52;            % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
flag   = 'scale';       % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2], [0 1 0], ...
                             [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
